### PR TITLE
No key fix

### LINKED ISSUE #35: handleInvalidVote() called when it shouldn't
When I create a new vote and click on it to see its info, the following error is printed in Logcat:
```
2020-04-25 00:36:58.979 10183-10183/nl.tudelft.trustchain E/vote_debug: Encountered an invalid voting block with ID 4c69624e61434c504b3a4342c771df6cc1c55ec5fd329619b37b7255a6ecc2b07235b84672d4bab34146b5ba6b0c28ffeaa9a73d853c78d7f40d92d127ba6bc8107df68cb13aa80e855d.3.The reason for invalidity was: Voting JSON did not have a value for key 'VOTE_REPLY'.
2020-04-25 00:36:59.026 10183-10183/nl.tudelft.trustchain E/vote_debug: Encountered an invalid voting block with ID 4c69624e61434c504b3a4342c771df6cc1c55ec5fd329619b37b7255a6ecc2b07235b84672d4bab34146b5ba6b0c28ffeaa9a73d853c78d7f40d92d127ba6bc8107df68cb13aa80e855d.3.The reason for invalidity was: Voting JSON did not have a value for key 'VOTE_REPLY'.
```
There is however nothing going wrong in the UI and I can still cast a vote on the proposal, see stats etc. It's also strange that the logcat is printed twice.

It is printed in line 243 in `trustchain-superapp\common\src\main\java\nl\tudelft\trustchain\common\util\VotingHelper.kt`

### PR DESCRIPTION
**Pull request by emieldesmidt**
As mentioned in issue #35 , a lot of errors where logged when they shouldn't. The reason for this is that a getter was used to check if something was present. If a field was not present, it would produce an error. So I've written a method that checks if this field is present, and returns an appropriate boolean value. This method is now also used by the getter before attempting to get a field.

The other changes you can see are android studio reformat suggestions.

closes #35

### CODE REVIEW

File: common/src/main/java/nl/tudelft/trustchain/common/util/VotingHelper.kt [hunk 1]
```diff
@@ -237,14 +245,17 @@ class VotingHelper(
     }
 
     /**
-     * Return the string value for a JSON tag in a voting block.
+     * Checks if a block possesses a specific attribute, without retiring it explicitly
```
Comment (PraveshMoelchand) [inline common/src/main/java/nl/tudelft/trustchain/common/util/VotingHelper.kt:248]: Typo in ‘retiring’?

Comment (emieldesmidt) [reply common/src/main/java/nl/tudelft/trustchain/common/util/VotingHelper.kt:248]: jep, should be retrieve

**Comment by PraveshMoelchand** [comment]
As with previous PRs, let's merge the oldest open PRs(#38 and #39)first before merging this one

**Comment by KoningR** [comment]
Works fine, no more spamming of the logs.

**Comment by erwinvanthiel** [comment]
Nice fix!

**Comment by PraveshMoelchand** [comment]
I assume the above two comments are approvals. Ready to merge!
